const doramasData = [
{
    id: 1,
    title: "Uma Advogada Extraordinária",
    description: "Uma jovem advogada brilhante com memória excepcional e uma forma única de enxergar o mundo. Sendo uma pessoa autista, ela enfrenta desafios para se adaptar ao ambiente jurídico, mas conquista seu espaço com inteligência, dedicação e empatia. Um dorama emocionante sobre inclusão, justiça e aceitação.",
    image: "assets/images/advogada-extraordinaria.jpg",
    rating: "10.0",
    year: "2022",
    episodes: "16",
    genres: "Drama, Justiça",
    category: "Drama"
 },
 {
    id: 2,
    title: "Pousando no Amor",
    description: "A história de Yoon Se-ri, uma empresária sul-coreana que, após um acidente de parapente,e cai na Coreia do Norte e conhece o capitão Ri Jeong-hyeok. Enquanto ele tenta ajudá-la a voltar para casa, os dois acabam descobrindo um amor inesperado capaz de ultrapassar fronteiras.",
    image: "assets/images/pousando-no-amor.jpg",
    rating: "9.8",
    year: "2019",
    episodes: "16",
    genres: "Romance, Drama",
    category: "Romance"
},
{
    id: 3,
    title: "Beleza Verdadeira",
    description: "Uma estudante de ensino médio que sofre bullying devido à sua aparência domina a arte da maquiagem, transformando-se na garota mais bonita da escola. Entre amizades, descobertas e um triângulo amoroso, ela aprende sobre autoestima, aceitação e o verdadeiro significado da beleza.",
    image: "assets/images/beleza-verdadeira.jpg",
    rating: "8.6",
    year: "2020",
    episodes: "16",
    genres: "Comédia, Romance",
    category: "Comédia"
},
{
    id: 4,
    title: "Hometown Cha-Cha-Cha",
    description: "Yoon Hye-jin é uma dentista da cidade grande que se muda para um vilarejo litorâneo e abre seu próprio consultório. Lá, ela conhece Hong Du-sik, um rapaz conhecido como faz-tudo da vila, que possui uma personalidade completamente diferente da sua. Entre diferenças, encontros e descobertas, os dois encontram um amor inesperado.",
    image: "assets/images/hometown-cha-cha-cha.jpg",
    rating: "8.0",
    year: "2021",
    episodes: "16",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 5,
    title: "Médicos em Colapso",
    description: "Yeo Jung-woo e Nam Ha-neul eram grandes promessas da medicina, mas acabam enfrentando uma fase difícil após acontecimentos que mudam suas vidas. Quando se reencontram em um momento de crise, os dois encontram apoio um no outro e descobrem um novo caminho de cura, amizade e amor.",
    image: "assets/images/medicos-em-colapso.jpg",
    rating: "8.0",
    year: "2024",
    episodes: "16",
    genres: "Romance, Médico",
    category: "Romance"
},
{
    id: 6,
    title: "Miss Night and Day",
    description: "Lee Mi-jin é uma jovem que sonha em conseguir um emprego estável, mas sua vida muda quando ela passa a viver uma transformação misteriosa: durante o dia, assume a aparência de uma mulher mais velha e, à noite, volta à sua juventude.",
    image: "assets/images/miss-night-and-day.jpg",
    rating: "8.0",
    year: "2024",
    episodes: "16",
    genres: "Mistério, Fantasia, Comédia",
    category: "Suspense"
},
{
    id: 7,
    title: "Olá Sou Eu",
    description: "Ban Ha-ni é uma mulher de 37 anos que perdeu a confiança em si mesma após enfrentar diversas dificuldades na vida. Um dia, ela encontra sua versão mais jovem, cheia de sonhos e coragem, que a ajuda a reencontrar sua autoestima e a enfrentar seus medos. Um dorama emocionante sobre recomeços, cura e amor próprio.",
    image: "assets/images/ola-sou-eu.jpg",
    rating: "8.0",
    year: "2021",
    episodes: "16",
    genres: "Fantasia, Comédia, Romance",
    category: "Fantasia"
},
{
    id: 8,
    title: "Quando o Telefone Toca",
    description: "Baek Sa-eon, um porta-voz político de uma família poderosa, e Hong Hee-joo, uma intérprete de linguagem de sinais, vivem um casamento de aparências. Quando uma ligação misteriosa muda suas vidas, segredos começam a surgir e os dois precisam enfrentar desafios que revelam novos sentimentos entre eles.",
    image: "assets/images/quando-o-telefone-toca.jpg",
    rating: "8.0",
    year: "2024",
    episodes: "12",
    genres: "Suspense, Romance, Drama",
    category: "Suspense"
},
{
    id: 9,
    title: "Rainha das Lágrimas",
    description: "Hong Hae-in, uma poderosa herdeira de um grande grupo empresarial, e Baek Hyun-woo, um advogado de origem simples, enfrentam uma crise em seu casamento após anos juntos. Em meio a desafios, eles redescobrem o amor, o valor da família e a importância de permanecerem unidos.",
    image: "assets/images/rainha-das-lagrimas.jpg",
    rating: "8.0",
    year: "2024",
    episodes: "16",
    genres: "Drama, Romance",
    category: "Drama"
},
{
    id: 10,
    title: "Uma Dose Diária de Sol",
    description: "Jung Da-eun é uma enfermeira dedicada que começa a trabalhar em uma ala de saúde mental, onde aprende sobre as histórias e desafios dos pacientes. Ao lidar com diferentes realidades, ela também enfrenta suas próprias dificuldades e descobre a importância da empatia, cuidado e esperança.",
    image: "assets/images/uma-dose-diaria-de-sol.jpg",
    rating: "8.0",
    year: "2023",
    episodes: "12",
    genres: "Drama, Médico, Psicológico",
    category: "Drama"
},
{
    id: 11,
    title: "O Amor Mora ao Lado",
    description: "Uma mulher decide recomeçar sua vida e acaba reencontrando um antigo conhecido que mora ao lado. Entre lembranças, conflitos e novos sentimentos, os dois descobrem que o amor pode estar mais perto do que imaginavam.",
    image: "assets/images/o-amor-mora-ao-lado.jpg",
    rating: "9.0",
    year: "2024",
    episodes: "16",
    genres: "Romance, Comédia, Drama",
    category: "Romance"
},
{
    id: 12,
    title: "Apesar de Tudo, Amor",
    description: "A história de uma jovem que não acredita mais no amor e um rapaz que gosta de relacionamentos sem compromisso. Mesmo com personalidades diferentes, eles acabam envolvidos em uma conexão difícil de ignorar.",
    image: "assets/images/apesar-de-tudo-amor.jpg",
    rating: "8.7",
    year: "2021",
    episodes: "10",
    genres: "Romance, Drama",
    category: "Romance"
},
{
    id: 13,
    title: "Sorriso Real",
    description: "Um herdeiro de um grande grupo hoteleiro e uma funcionária conhecida pelo seu sorriso verdadeiro acabam se aproximando enquanto enfrentam desafios profissionais e pessoais.",
    image: "assets/images/sorriso-real.jpg",
    rating: "9.1",
    year: "2023",
    episodes: "16",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 14,
    title: "A Love So Beautiful",
    description: "Shin Sol-i é uma estudante alegre e cheia de energia que nutre um amor pelo seu vizinho e colega de escola, Cha Heon, um jovem inteligente e reservado. Ao longo dos anos, os dois vivem descobertas, amizades e desafios enquanto aprendem sobre o primeiro amor e o crescimento juntos.",
    image: "assets/images/a-love-so-beautiful.jpg",
    rating: "8.5",
    year: "2020",
    episodes: "24",
    genres: "Romance, Escolar, Comédia",
    category: "Romance"
},
{
    id: 15,
    title: "O Amor Volta Para Casa",
    description: "Byeon Moo-jin, um homem que desapareceu da vida da família após enfrentar dificuldades, retorna anos depois como um homem rico e bem-sucedido. Ao reencontrar sua ex-esposa e filha, ele tenta reconstruir os laços familiares enquanto antigos sentimentos e novos desafios surgem.",
    image: "assets/images/o-amor-volta-para-casa.jpg",
    rating: "8.9",
    year: "2024",
    episodes: "12",
    genres: "Drama, Romance, Família",
    category: "Drama"
},
{
    id: 16,
    title: "Pretendente Surpresa",
    description: "Shin Ha-ri aceita ir a um encontro às cegas no lugar de sua amiga para ajudá-la, mas descobre que o pretendente é Kang Tae-moo, o CEO da empresa onde trabalha. O que começa como uma mentira acaba se transformando em um romance inesperado, cheio de humor, encontros divertidos e descobertas.",
    image: "assets/images/pretendente-surpresa.jpg",
    rating: "9.3",
    year: "2022",
    episodes: "12",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 17,
    title: "Celebrity",
    description: "Seo A-ri é uma jovem que entra no mundo dos influenciadores digitais e descobre o lado glamouroso e perigoso da fama. Ao conquistar milhões de seguidores, ela enfrenta disputas, segredos e a pressão por reconhecimento em uma realidade onde a popularidade vale tudo.",
    image: "assets/images/celebrity.jpg",
    rating: "8.6",
    year: "2023",
    episodes: "12",
    genres: "Drama, Suspense",
    category: "Drama"
},
{
    id: 18,
    title: "Beijo Explosivo",
    description: "Go Da-rim é uma mulher determinada que acaba se envolvendo em uma situação inesperada após um beijo impulsivo com Gong Ji-hyeok, um homem sério e reservado. Entre mal-entendidos, desafios no trabalho e sentimentos que surgem aos poucos, os dois descobrem uma conexão inesperada.",
    image: "assets/images/beijo-explosivo.jpg",
    rating: "8.4",
    year: "2025",
    episodes: "12",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 19,
    title: "Investimento de Risco",
    description: "Uma especialista em investimentos e um profissional do mercado financeiro se aproximam enquanto enfrentam desafios de carreira e sentimentos inesperados.",
    image: "assets/images/investimento-de-risco.jpg",
    rating: "8.3",
    year: "2022",
    episodes: "12",
    genres: "Romance, Drama, Negócios",
    category: "Romance"
},
{
    id: 20,
    title: "Uma Seul Desconhecida",
    description: "Yoo Mi-ji e Yoo Mi-rae são irmãs gêmeas com personalidades e vidas completamente diferentes. Após uma troca inesperada de identidades, elas passam a enfrentar novos desafios e descobrem segredos, sentimentos e novas formas de enxergar a si mesmas e a vida.",
    image: "assets/images/uma-seul-desconhecida.jpg",
    rating: "8.8",
    year: "2024",
    episodes: "12",
    genres: "Drama, Romance",
    category: "Drama"
},
{
    id: 21,
    title: "A Lição",
    description: "Moon Dong-eun sofreu uma intensa violência escolar no passado e passou anos planejando sua vingança contra aqueles que destruíram sua juventude. Ao colocar seu plano em ação, ela enfrenta seus traumas e busca justiça em uma história marcada por dor, superação e coragem.",
    image: "assets/images/a-licao.jpg",
    rating: "9.4",
    year: "2022",
    episodes: "16",
    genres: "Drama, Suspense, Vingança",
    category: "Drama"
},
{
    id: 22,
    title: "Amor e Batatas",
    description: "Kim Mi-kyeong é uma pesquisadora apaixonada por batatas que trabalha em um laboratório rural. Sua rotina muda com a chegada de So Baek-ho, um novo diretor que possui uma personalidade completamente diferente da sua. Entre conflitos, descobertas e convivência, os dois desenvolvem uma conexão inesperada.",
    image: "assets/images/amor-e-batatas.jpg",
    rating: "8.2",
    year: "2025",
    episodes: "12",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 23,
    title: "Gostinho de Amor",
    description: "Han Beom-woo é um jovem herdeiro de uma grande empresa de alimentos que busca o sucesso a qualquer custo, enquanto Mo Yeon-joo é uma chef apaixonada pela culinária simples e autêntica. Ao se encontrarem em um pequeno restaurante, os dois descobrem que suas diferenças podem aproximá-los em uma história de sabores, sonhos e amor.",
    image: "assets/images/gostinho-de-amor.jpg",
    rating: "8.5",
    year: "2025",
    episodes: "12",
    genres: "Romance, Comédia, Culinária",
    category: "Romance"
},
{
    id: 24,
    title: "Diva à Deriva",
    description: "Seo Mok-ha é uma jovem que sonha em se tornar cantora, mas acaba presa em uma ilha deserta por 15 anos após um acidente. Ao ser resgatada, ela tenta reconstruir sua vida e seguir seu sonho de brilhar nos palcos, enfrentando desafios, reencontros e novas descobertas.",
    image: "assets/images/diva-a-deriva.jpg",
    rating: "9.0",
    year: "2023",
    episodes: "12",
    genres: "Romance, Música, Drama",
    category: "Romance"
},
{
    id: 25,
    title: "Namorado por Assinatura",
    description: "Han Yoo-jin é uma jovem que entra em um serviço de namoro por assinatura para resolver situações da sua vida pessoal. Ao conhecer um parceiro contratado para fingir ser seu namorado, ela acaba se envolvendo em uma relação inesperada, descobrindo novos sentimentos e desafios pelo caminho.",
    image: "assets/images/namorado-por-assinatura.jpg",
    rating: "8.4",
    year: "2025",
    episodes: "10",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 26,
    title: "Amor Enrolado",
    description: "Park Se-ri é uma adolescente apaixonada que sonha em conquistar o garoto mais popular da escola, mas acredita que precisa mudar sua aparência para ser aceita. Uma história sobre primeiro amor, autoestima e descobrir o verdadeiro valor de ser quem você é.",
    image: "assets/images/amor-enrolado.jpg",
    rating: "8.1",
    year: "2024",
    episodes: "12",
    genres: "Romance, Comédia",
    category: "Romance"
},
{
    id: 27,
    title: "Alice in Borderland",
    description: "Arisu é um jovem que, junto com seus amigos, acaba misteriosamente transportado para uma Tóquio deserta onde precisam participar de jogos perigosos para sobreviver. Enquanto enfrentam desafios mortais, eles buscam respostas sobre esse mundo desconhecido e descobrem segredos sobre suas próprias vidas.",
    image: "assets/images/alice-in-borderland.jpg",
    rating: "9.2",
    year: "2020",
    episodes: "8",
    genres: "Ação, Suspense, Ficção Científica",
    category: "Suspense"
},
{
    id: 28,
    title: "The Fabulous",
    description: "Quatro amigos trabalham no mundo da moda enquanto enfrentam desafios profissionais. Eles vivem momentos de amor, amizade e descobertas em meio ao universo glamouroso da moda.",
    image: "assets/images/the-fabulous.jpg",
    rating: "8.0",
    year: "2022",
    episodes: "8",
    genres: "Romance, Moda, Drama",
    category: "Romance"
},
{
    id: 29,
    title: "Typhoon Boss",
    description: "Durante a crise financeira de 1998, Kang Tae-poong assume inesperadamente a empresa da família e precisa lutar para manter o negócio de pé. Entre desafios, responsabilidades e mudanças no mundo dos negócios, ele cresce como líder e descobre o verdadeiro significado de família, perseverança e sucesso.",
    image: "assets/images/typhoon-boss.jpg",
    rating: "8.6",
    year: "2025",
    episodes: "16",
    genres: "Drama, Negócios",
    category: "Drama"
},
{
    id: 30,
    title: "O Amor Pode Ser Traduzido?",
    description: "Uma famosa atriz e um talentoso intérprete começam a trabalhar juntos em uma viagem internacional. Enquanto ele traduz idiomas para ela, os dois descobrem que traduzir sentimentos pode ser muito mais complicado do que traduzir palavras.",
    image: "assets/images/o-amor-pode-ser-traduzido.jpg",
    rating: "8.8",
    year: "2025",
    episodes: "12",
    genres: "Romance, Comédia, Drama",
    category: "Romance"
}
];  